server:
  port: 8084

spring:
  profiles:
    active: local
    include:
      - SECRET

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  devtools:
    livereload:
      enabled: true # 서버 자동 시작